source 'https://rubygems.org'

gem 'rake'
gem 'rake_cloudspin'
gem 'rake_docker'
# gem 'rake_cloudspin', :path => '../rake_cloudspin'
gem 'aws_ssh_key'
gem 'inspec'
gem 'semantic', '~> 1.4', '>= 1.4.1'
