---
vars:
  estate: "%{hiera('estate')}"
  component: "%{hiera('component')}"

  region: "%{hiera('region')}"
  aws_profile: "%{hiera('aws_profile')}"
  assume_role_arn: "%{hiera('spin_delivery_manager_role_arn')}"

  repo_bucket_name: "repo-%{hiera('estate')}-%{hiera('component')}"

  github_owner: "%{hiera('github_owner')}"
  github_repo: "%{hiera('github_repo')}"
  github_branch: "%{hiera('github_branch')}"
  github_oath_token: "%{hiera('github_oath_token')}"

state:
  type: local
